spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver
    application:
      description: Your Application Description

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    name: auth-server
server:
  port: 9000
