spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    name: payment-service
server:
  port: 8060

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.bogdan.ecommerce.notification.PaymentNotificationRequest
application:
  config:
    product-url: http://localhost:8222/api/v1/products
