spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro
    username: postgres
    password: rootroot
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    name: user-service
server:
  port: 8070